- name: start
  type: command
  text: |
    <b>ğŸ‘‹ OlÃ¡, {firstName}!</b>
    
    ğŸ¤– Eu estou aqui para automatizar as descriÃ§Ãµes das suas postagens no Canal!
    
    âœ¨ Com o sistema de <b>Legendas Inteligentes</b>, suas publicaÃ§Ãµes sempre terÃ£o descriÃ§Ãµes personalizadas e organizadas.
    
    ğŸ“– Consulte a aba  Como Usar para aprender a configurar tudo rapidamente!
  buttons:
    - - text: "â„¹ï¸ Sobre"
        callback_data: "about"

- name: about
  text: |
    <b>â„¹ï¸ Sobre o Bot</b>
    
    <blockquote>ğŸ“Œ <b>VersÃ£o:</b> <i>{botVersion}</i>
    âš™ï¸ <b>Desenvolvido Por:</b> <i>{ownerUser}</i></blockquote>
    
    
    ğŸš€ Este bot foi criado para facilitar a adiÃ§Ã£o de <b>legendas automÃ¡ticas</b> em postagens de canais, tornando a gestÃ£o de conteÃºdo mais eficiente e dinÃ¢mica.
    
    ğŸ“¢ Para aprender a configurar, consulte a aba <a href='tg://user?id={botId}'>Ajuda</a>!"
  buttons:
    - - text: "ğŸ  InÃ­cio"
        callback_data: "start"
      - text: "â“ Ajuda"
        callback_data: "help"